### ISSUE TITLE
New version on glibc requires uses exp10f instead of pow10f

### ISSUE THREAD

**Issue by guysoft** [moddevices/caps-lv2#16] opened 2018-09-11 01:53 UTC
Current workaround is to run  
```
sed 's/pow10f/exp10f/g' dsp/v4f_IIR2.h -i
```

**Comment by trebmuh** [comment] 2018-09-11 08:28
Duplicate of https://github.com/moddevices/caps-lv2/pull/15

**Comment by guysoft** [comment] 2018-09-11 11:45
Should I close? can move the workaround there

**Comment by trebmuh** [comment] 2018-09-11 12:05
It depends of the moddevices people. The purpose of my last message was to be informational.

**Closed** 2019-04-30 09:38 UTC
